language: r
sudo: false
cache: packages
env:
  global:
    secure: "E+V2O0xM1aMOqSHIGZN5GtbxBvFp72GbALYx9oCnNXs5cdFFmYvhSIWvPBg8ilS6LbHZcWaOT9AaTEnK0JFZpzsl7ajIV07OODw0hOnO0n971rlZGGe0MLuS9rJ/8KVEnhqWmXjG9mGifSY8ThKvE/GN4dy+GgTGSETojufEwpiuJmFvoCkguCjrC15Kk7ZsBD44KVBauvk4XAs1YNSHk4dhfgcmTsIlMP6vOHZ3maryKpOyPevbhM3gQQEPUwQ1ZlicLDQ8QqtXmxVurzkY3aIPnrQGDg5AAynUj4dkoiqD2JJIU/bj4et11TTW/Q+RMofH44lqlWp2uDbpaYsbPCi9iuhbEMp1dwFdC/TH5tVaIYAut2g4miv6sCfPZIBGbwOPO67kBzCIcVZzA4bkIuoaIWf1YG8wRecfjTzs7QV6quOONnXjr2okRs4InBS+IZ57alDpJ+5LpC7lbrdD29x9MvYsGwVhVQzhxoxPxZ35XLP2SULOBxsCe1MPj5Yfup2B8Oh3wPYrVyD31FlAxDfb6Xm2EIxlIm7XjndnezipTLbXVjUgcfaOAJbYSmmsR+0vxWFpC6Bf8+zuIW4zEgmjnZ47RYCyXPN+srFw287HS4mrJ4KoWoSFHjnRuwQLNy7XoBtfvzhwGMJj2OW7/vvAtJDUOvZm0xFZh9pznZs="
r_github_packages:
  - rstudio/rmarkdown
install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"
branches:
  only:
    - master
script:
  - make
after_success:
  - tools/pack auto/latex info2.tex info2_files/figure-latex/* sprawozdanie.cls znak.tex
  - tools/pack auto/html info2.html info2_files/*
  - tools/pack auto/word info2.docx
  - tools/pack auto/pdf info2.pdf
